# Generated by Django 3.2.4 on 2023-09-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_category_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cpic',
            field=models.ImageField(null=True, upload_to='static/category/'),
        ),
    ]
