# Generated by Django 3.2.4 on 2023-09-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_event_event_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='event_des',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='event_des',
            field=models.TextField(null=True),
        ),
    ]
