# Generated by Django 3.2.4 on 2023-09-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20230915_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=200, null=True)),
                ('passwd', models.CharField(max_length=100, null=True)),
                ('upic', models.ImageField(null=True, upload_to='static/profile')),
                ('address', models.TextField(null=True)),
            ],
        ),
    ]
