# Generated by Django 3.2.4 on 2023-09-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20230918_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknow',
            name='userid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
