# Generated by Django 3.2.4 on 2023-10-11 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_booknow_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booknow',
            old_name='event_date',
            new_name='event_dates',
        ),
    ]
