# Generated by Django 3.2.4 on 2023-10-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_event_date_booknow_event_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknow',
            name='event_dates',
            field=models.DateField(null=True),
        ),
    ]
